---
name: ci

on: [pull_request, push]

permissions:
    contents: write

jobs:
    format:
        uses: alexiszamanidis/.github/.github/workflows/prettier.yml@master
        with:
            node-version: "24"
